linters:
  enable:
    # Default linters plus these:
    - golint
    - revive
    - gofmt
    - exhaustive
    - goimports
    - gci
    - nakedret

linters-settings:
  gci:
    sections:
      - standard
      - default

run:
  timeout: 2m

