linters:
  enable:
    # Default linters plus these:
    - revive
    - gofmt
    - exhaustive
    - goimports
    - gci
    - nakedret

linters-settings:
  gci:
    sections:
      - standard
      - default
  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    # Default: false in initial versions of golangci integration
    default-signifies-exhaustive: true

run:
  timeout: 3m

