language: go

go:
  - "1.16.x"

services:
  - docker

jobs:
  include:
    - name: Lint
      script: make lint
    - name: Unit Tests
      script: make coverage-unit
    - name: Tests
      script: make test
      if: fork = false AND type = push  # Don't run int tests too much on the same account in parallel, risks service name conflict failures
    #- name: Test End-to-end  # TODO Re-enable once an e2e env is set up.
    #  script: make test-e2e
    - name: Release Validation
      script: make validate-release RELEASE_VERSION=1000.0.0  # Arbitrarily high version, just used for quick validation
    - name: Release
      stage: release
      script: make -e RELEASE_VERSION="${TRAVIS_TAG/v}" release
      if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      deploy:
        - provider: releases
          api_key: "$RELEASE_GH_TOKEN"
          file: out/*
          file_glob: true
          skip_cleanup: true
          overwrite: true
          on:
            all_branches: true # earlier 'if:' limits this
            repo: IBM/cloud-operators

notifications:
  email: false
