language: go

go:
  - "1.14.x"

services:
  - docker

jobs:
  include:
    - name: Lint
      script: make lint
    - name: Test
      script: make coverage
      if: type = pull_request  # Don't run int tests on the same account in parallel, risks name conflicts
    - name: Test End-to-end
      script: make test-e2e
    - name: Release
      stage: release
      script: make -e RELEASE_VERSION="${TRAVIS_TAG/v}" release
      if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      deploy:
        - provider: releases
          api_key: "TODO"
          file: out/*
          file_glob: true
          skip_cleanup: true
          overwrite: true
          draft: true
          on:
            all_branches: true # earlier 'if:' limits this

notifications:
  email: false
