
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ibmcloud.ibm.com.my.domain
  resources:
  - bindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibmcloud.ibm.com.my.domain
  resources:
  - bindings/status
  verbs:
  - get
  - patch
  - update
