apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: mydb2
spec:
  plan: free
  serviceClass: dashdb-for-transactions
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-db2
spec:
  serviceName: mydb2
