apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: myes
spec:
  plan: standard
  serviceClass: databases-for-elasticsearch
  parameters:
  - name: members_disk_allocation_mb
    value: 307201
  - name: service_endpoints
    value: public
  tags:
  - booya
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-myes
spec:
  serviceName: myes
  role: Editor