apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: myetcd
spec:
  plan: standard
  serviceClass: databases-for-etcd
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-etcd
spec:
  serviceName: myetcd
