apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: myiot
spec:
  plan: iotf-service-free
  serviceClass: iotf-service
  serviceClassType: CF
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-iot
spec:
  serviceName: myiot
