apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: mymessagehubcf
spec:
  plan: standard
  serviceClass: messagehub
  serviceClassType: CF
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-messagehubcf
spec:
  serviceName: mymessagehubcf
