apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
  name: mypostgresql
spec:
  plan: standard
  serviceClass: databases-for-postgresql
---
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
  name: binding-postgresql
spec:
  serviceName: mypostgresql
