apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: mystreams
spec:
  plan: entry-container-lite
  serviceClass: streaming-analytics
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-streams
spec:
  serviceName: mystreams
