apiVersion: ibmcloud.ibm.com/v1beta1
kind: Service
metadata:
  name: mytranslator
  annotations:
    ibmcloud.ibm.com/self-healing: enabled
spec:
  plan: lite
  serviceClass: language-translator
---
apiVersion: ibmcloud.ibm.com/v1beta1
kind: Binding
metadata:
  name: binding-translator
spec:
  serviceName: mytranslator
