# Constants used to package the operator for operator hub

operator_name: ibmcloud-operator
channel_name: alpha
maturity: alpha
image: cloudoperators/ibmcloud-operator
crd:
    - kind: Service
      description: Represents an instance of a Service resource on IBM Cloud.
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Service",
            "metadata": {
            "name": "mytranslator"
            },
            "spec": {
            "serviceClass": "language-translator",
            "plan": "lite"
            }
        }
      resources:
        - kind: Secret
          version: v1
        - kind: ConfigMap
          version: v1
        - kind: Binding
          version: v1alpha1
        - kind: Service
          version: v1alpha1     
      specDescriptors:        
        - description: Service class is the name of the service from the IBM Cloud Catalog
          displayName: Service Class
          path: serviceClass
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Plan for the service from the IBM Cloud Catalog
          displayName: Plan
          path: plan
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: ServiceClassType is set to CF if the service is CloundFoundry
          displayName: ServiceClassType
          path: serviceClassType
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: ExternalName for the service as it appears on IBM Cloud
          displayName: ExternalName
          path: externalName
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: Parameters for the service 
          displayName: Parameters
          path: parameters
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Tags for the service 
          displayName: Tags
          path: tags
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current context for the service (resource group, resource group ID, user, region, org, space)
          displayName: Context
          path: context
          x-descriptors:
            - 'urn:alm:descriptor:text'    
      statusDescriptors:
        - description: Detailed message on current status
          displayName: Message
          path: message
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current plan for service
          displayName: Plan
          path: plan
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Current service class
          displayName: Service Class
          path: serviceClass
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Current ServiceClassType, set to CF if the service is CloundFoundry
          displayName: ServiceClassType
          path: serviceClassType
          x-descriptors:
            - 'urn:alm:descriptor:text'  
        - description: Current state for the service
          displayName: State
          path: state
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current context for the service (resource group, resource group ID, user, region, org, space)
          displayName: Context
          path: context
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Instance ID for the service
          displayName: Instance ID
          path: instanceId
          x-descriptors:
            - 'urn:alm:descriptor:text'  
        - description: ExternalName for the service as it appears on IBM Cloud
          displayName: ExternalName
          path: externalName
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Parameters for the service 
          displayName: Parameters
          path: parameters
          x-descriptors:
            - 'urn:alm:descriptor:text'   
        - description: Tags for the service 
          displayName: Tags
          path: tags
          x-descriptors:
            - 'urn:alm:descriptor:text'  
        - description: DashboardURL for the service 
          displayName: DashboardURL
          path: dashboardURL
          x-descriptors:
            - 'urn:alm:descriptor:text'     
    - kind: Binding
      description: Represents an instance of a service binding resource on IBM Cloud. A Binding creates a secret with the service instance credentials.
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Binding",
            "metadata": {
            "name": "mytranslator-binding"
            },
            "spec": {
            "serviceName": "mytranslator"
            }
        }
      resources:
        - kind: Secret
          version: v1
        - kind: ConfigMap
          version: v1
        - kind: Binding
          version: v1alpha1
        - kind: Service
          version: v1alpha1
      specDescriptors:        
        - description: Name of the service resource to bind
          displayName: Service Name
          path: serviceName
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Name of the secret where credentials will be stored
          displayName: Secret Name
          path: secretName
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: ServiceNamespace of the service resource to bind
          displayName: ServiceNamespace
          path: serviceNamespace
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Role for the credentials
          displayName: Role
          path: role
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Alias for the credentials to be aliased
          displayName: Alias
          path: alias
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Parameters for the binding 
          displayName: Parameters
          path: parameters
          x-descriptors:
            - 'urn:alm:descriptor:text'  
      statusDescriptors:
        - description: Detailed message on current status
          displayName: Message
          path: message
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current state for the binding
          displayName: State
          path: state
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Name of generated secret with service credentials
          displayName: Secret Name
          path: secretName
          x-descriptors:
            - 'urn:alm:descriptor:text'
            - 'urn:alm:descriptor:io.kubernetes:Secret'
            - 'binding:env:object:secret'   
        - description: Instance ID for the service
          displayName: InstanceID
          path: instanceId
          x-descriptors:
            - 'urn:alm:descriptor:text'     
        - description: Key Instance ID for the credentials
          displayName: KeyInstanceID
          path: keyInstanceId
          x-descriptors:
            - 'urn:alm:descriptor:text' 
     
  