apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [{"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Service", "metadata": {"name": "myeventstreams"}, "spec": {"externalName": "myeventstreams", "serviceClass": "messagehub", "plan": "standard"}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Binding", "metadata": {"name": "myeventstreams-binding"}, "spec": {"serviceName": "myeventstreams"}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Function", "metadata": {"name": "greetings"}, "spec": {"codeURI": "https://raw.githubusercontent.com/apache/incubator-openwhisk-catalog/master/packages/utils/echo.js", "parameters": [{"name": "message", "value": "Bonjour"}], "runtime": "nodejs:6"}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Invocation", "metadata": {"name": "echo-invocation"}, "spec": {"function": "/whisk.system/utils/echo", "parameters": [{"name": "message", "value": "Hello World"}], "finalizer": {"function": "/whisk.system/utils/echo", "parameters": [{"name": "message", "value": "Bye World"}]}}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Package", "metadata": {"name": "mh-publish"}, "spec": {"bind": "/whisk.system/messaging", "service": "message-hub"}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Trigger", "metadata": {"name": "image-uploaded"}, "spec": {"feed": "openwhisk-cloudant/changes"}}, {"apiVersion": "ibmcloud.ibm.com/v1alpha1", "kind": "Rule", "metadata": {"name": "my-rule"}, "spec": {"trigger": "image-uploaded", "action": "hello-world"}}]
    capabilities: Full Lifecycle
    categories: Cloud Provider
    certified: 'false'
    containerImage: registry.ng.bluemix.net/seed/cloud-operators:0.1.1
    createdAt: '2019-06-11T14:12:11Z'
    description: The IBM Cloud Service Operator provides a Kubernetes CRD-Based API
      to manage the lifecycle of IBM public cloud services.
    support: IBM
  name: ibmcloud-operator.v0.1.1
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: IT Represents an instance of a Service resource on IBM Cloud.
      displayName: Service
      kind: Service
      name: services.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an instance of a Service binding resource on IBM Cloud.
        A Binding creates a secret with the service instance credentials.
      displayName: Binding
      kind: Binding
      name: bindings.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an IBM Cloud Function action.
      displayName: Function
      kind: Function
      name: functions.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an IBM Cloud Function activation.
      displayName: Invocation
      kind: Invocation
      name: invocations.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an IBM Cloud Function package.
      displayName: Package
      kind: Package
      name: packages.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an IBM Cloud Function trigger.
      displayName: Trigger
      kind: Trigger
      name: triggers.ibmcloud.ibm.com
      version: v1alpha1
    - description: Represents an IBM Cloud Function rule.
      displayName: Rule
      kind: Rule
      name: rules.ibmcloud.ibm.com
      version: v1alpha1
  description: "The IBM Cloud Operator provides a Kubernetes CRD-Based API to manage\
    \ the lifecycle of IBM public cloud services. You can provision and bind to any\
    \ of the 130+ IBM public cloud services, and create and manage service  specific\
    \ resources, such as event streams topics and cloud object store buckets.\n##\
    \ Supported Features\n* **Supports both RC-enabled and legacy services** - You\
    \ can provision any service available in the IBM Cloud catalog.\n\n* **Bindings\
    \ Managment** - Automatically creates secrets with the credentail to bind to any\
    \ provisioned service.\n* **Bind Only Mode** - You do not need to provision a\
    \ service to bind to it. You can bind to  existing services.\n## Requirements\n\
    You can install the operator in any Kubernetes cluster enabled with the Operator\
    \ Lifecycle Manager and  Operator Marketplace. You need to have an IBM Cloud account\
    \ and the IBM Cloud CLI. \nBefore installing the operator, you need to login to\
    \ IBM cloud with the IBM Cloud CLI, set a target environment with the `ibmcloud\
    \ target` command and generate your IBM Cloud API key and  setup your default\
    \ cloud context with the following commands:\n\n    IC_APIKEY=$(ibmcloud iam api-key-create\
    \ icop-key -d \"Key for IBM Cloud Operator\" | grep \"API Key\" | awk '{ print\
    \ $3 }')\n    IC_TARGET=$(ibmcloud target) \\\n    IC_ORG=$(echo \"$IC_TARGET\"\
    \ | grep Org | awk '{print $2}')  \\\n    IC_SPACE=$(echo \"$IC_TARGET\" | grep\
    \ Space | awk '{print $2}') \\\n    IC_REGION=$(echo \"$IC_TARGET\" | grep Region\
    \ | awk '{print $2}') \\\n    IC_GROUP=$(echo \"$IC_TARGET\" | grep 'Resource'\
    \ | awk '{print $3}')\n    B64_APIKEY=$(echo -n $IC_APIKEY | base64)\n    B64_REGION=$(echo\
    \ -n $IC_REGION | base64)\n\nThen, create a secret with your API key with the\
    \ command:\n\n    cat <<EOF | kubectl create -f -\n    apiVersion: v1\n    kind:\
    \ Secret\n    metadata:\n        name: seed-secret\n        labels:\n        \
    \  seed.ibm.com/ibmcloud-token: \"apikey\"\n        namespace: default\n    type:\
    \ Opaque\n    data:\n        api-key: $B64_APIKEY\n        region: $B64_REGION\n\
    \    EOF\n\nFinally, create a config map to store your default context with the\
    \ command:\n\n    cat <<EOF | kubectl create -f -\n    apiVersion: v1\n    kind:\
    \ ConfigMap\n    metadata:\n      name: seed-defaults\n      namespace: default\n\
    \    data:\n      org: $IC_ORG\n      region: $IC_REGION\n      resourceGroup:\
    \ $IC_GROUP\n      space: $IC_SPACE\n    EOF\n"
  displayName: IBM Cloud Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAK8AAACvCAMAAAC8TH5HAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAB1UExURQAAAJGS77CC4pCS75yM64uV8pSQ7puA85OV87OB4auF5Hyd+H2c936b9n6b94Ca9n+b9n+b9n+b9qOJ56SI55yM6qSI536b96aH5q2D45mN64OZ9ZWQ7oyU8XWg+6uG5oqg/p6L6m+k/ZuY+3mr/6qQ9LqM80D8C0oAAAAbdFJOUwA67R4KKxMBBP6ak6vZgVtJxG5ot+hQ7YDVkwC2C58AAAuSSURBVHja7ZyJerK8EoCDCSTKjoiIS13of/+XeGYm4NLKrvj1OYxt7aa8TiazJZGxSSaZZJJJJvmcSCn/Eq7Cz79DLJk0rb+kXdM9nz0m/4p2mZufz3lAZvEn1HsGye2J9128h7/Gezj8Nd7D3+I9/xu8SjWHrS76bfN8A+NsYxjowCvbPN+QSGB6kWi6QHteyQLPfx+wYsH2eHSthgu05lXMy/PceRcwxtnjdnts4mjLq5hBceVdcVsya71FMeov0JIXMuQwR+DoXX5EMgf0uz2GrDYbb8mrmE+4Z/NdvDCApN+jX3uFdrySqfW70wzFbFLwWtVNkXa8ONlIvfx9Dk0xSyvYq0NpxasYJ9o8emcUVCw6EjGvuUpLXgfVm9cP1fAZp1yyCKeGBf8pB96g9jUZ57c6s1vIIAUfjXqY9eFg1yiuKJnOECzeW+TJm0+rxRGGWfcP7/dld8bZwqcp/dJqIs9hrJIJ/JD2abV5j1StfJn1/pofo/Kx0ae1KfAO7/Vld7anfVpf28M5kKPDc9kYLRW4RDhIwYV/PozVUAF39Qre3BmrvsM04nisjHHyJlUjZEOefuBj8UIA81zHfGJ84BYeHAP9LKseP1r5LNnvOlHeXJgqRZbUPzT97PHvBVb48VCX09W54du2u3ZJwjD0It/gqmCue/yoolm4b7tQjmohh7cGAWzHC8x/qOFOZmBG4bbERDkQrVYyiGP7iPwPLGrgsAofYbePonEJ2CHxAuvjxEjLvfUj7J1BaP0irY3i888SA63l3alWgwKjbXueZztOSBoucOE33huIZdsWHChXRds72O069PyHhSEBDiOynbAEBiGreCGJKoa5zT8GVBzt4QNgXc+wbq4YvW+hSMkDYNa4EYihWqlYtmouSsYTo4XvgWezHKDcI+7xuPbMMp7JH0GEfhZGRMDIG5FRtLG1IGCNvTp/d9nFZhMx/DXYH/cgSBv6SscM+Tyf0P450Lw+iCmbOGAMonOeO/XlMyTjgAsfmWAN9Y53RFy0hDAovXBDSBFBVAIHDdUJ2lre3J6AVG9Hcln5NQyKCUcrd390g5/BtjpNR2KNGwTVpRDSmk6et6jwCv0ScVhpxopxl3DBIjzVjrYk5gVuEPAaw7UP+aFV+0ex5Aq8y/hTYhiE/UXjhibrlBUisUm8hmHwqujuH3IqQLA/0dT+Af8Q34hT8du3QXlR4nrdkxhJ0554nwAXhpvj+hLUo2u/zWoJM1aXy70ZP8e97APWJ+WGbN1AXNP8tedAasM96PLu4Ik2jhpHZLkqgdGM5TNjuKzNnhkiUmneH8CSCe9wpXV429HDlCu7GcV9JwemWoEbWr3rGZx2iMs5F4+T3S1p89DoYGvkUeLCKC67m+uBsVwVuGpI+QVohGtZ6rHrU+Cu/UaP/ps4KY3iWhlipwNwd4Arh1WLCIy4lpA/2yiF4XZ9ehgMuaRgt7r6FMWiC9DuL64YWtyCrQKuEOLe1iJsG+eO2W8eo+POdrvVtdULrgG0Dbg76xW1uCDcm5GCguzDAeNlz0qPqgfzGunJeAl4aOug6KYQ7l2WhI7DZEMqZ7L5a1uBZWTQF3/QVHvmUosOBX0ZVkbfkgNtDYCbDcDVsIKbQYCJBCY/gak7FHQh+bqiX7LwsnuYfr1gqUTCUsPWgsWdF1H2I1/ZoYBMSLs3o3/blyke+FRiEPE9c1Huq9dpV60GWQNmvybSIrCnee0SGIlDJzJfVzwrttTq7bfkUNCSzV71a19pScNOGHrmi9pWV/Uue6lXYpEcBFfgslSOPG0MBTASc/YK3455PEqvyYY5r0G4AeH6gWHqSCyVxQ2s9ksJw9B/ATBYVUy8fdRL6ZhhlPo1HpIyHelM38OmCuA6oWvzwTah69DTbiW6qxdMCdPdAIGLbrC8lyIimxHRgrhQcA+cdoqluxXc0u7qhcTGNBAYeKkB9CTASfJjVuTo7mvoRsO676Ci+LRanVbd91YgLggp2GI1/kpRq7MAXnuDjBhC8Qpkl3UepwIXgblseDQq2XBcUK8bru0hGgbni7ynzrMNs1xOuJDmNQMAsfAI2B0CjOaAvKuuK2aES8C8XU8Sn98H9SKw12/SwfwVzNyArOLOL1lxEpO37/lKFujlpW3UfTSZwpxaQCkXb+JVd3OAAg1xrQ4vFGzC0MDrbuvLSGtRiSVYuonjeNU5MxMWAVudZzct1azdLmUXzGZLV7BCySxG6Zrq4MsFXqv79A7WiLu1OwwLFgElr7VA3LQjLtZnCCx7+KNo7a4BuG3lhRmKWXQ0LME40Gbxsqt6BQH3arExZ+viCl67Ib1rGHFLQPIQL7JFnHTjRfUCb68whR1mXM3dttpjcWvIAS6uNCRxlmVxxypeCVJw3wjl0/LzmrfaVG4kBgFT6ge57wJ4M7OTfmlNS4j+McpB4G2rTfBGkhAwp2UcWfB2cw/FFogBKQvxrhtTLMnMZYJiFG4eeLM0zVLRg3dIzmJvAbfRgiXjS81rXfeBLIE3TTuVQneZeH8Fb4HXFQ0rcGKJcsNFXsRdduYdViSQBQNy0LCilaSIu+R3TeqP8KKLQAXXzjgw3hR5l3erFvoldOOVr9Cv5eK6v1tzXch0UZfLNGEPvGQi3fU7tMi1m45PgCtb4Nin974Lftmd9yUtJZ94q/NgUG9KvA9rWOjgwKATMTqv3mpcbcDgQxaLRbpYyp+89/5tLMF98GTAVZsP4LfpAuXRYnALBwof+0AxejR0EVVpO4ARbvpz96D1GV7FvNoJB4lNDLiQOKofIQSTicQcnzeq5ZUsxTpi8ctQJeVrJmNj8wbEWxHhYNxjXff8UiT1vww1Oq9R59Dgz1gGb5Kff5a62jA/4tD222Ml75J4zd+8uglmfcQB76s2nktsM2w2z8p2yamWG90eTNrd9ly/ALnAtlP8LO5a1FdSo9sv7h3cVvGqGHkXT9Sr+3ZcjO4faNNYUMErkHf2tIeuqBNhjc0bHXEDoVHBa20qeRm1liw1Mq9H29z68Ard+hs7f0BzWD/3S8g7q+TV3RohR8VVLqq34pgR2G8NL9O8alx3Rrvy7Cr3q2LkXTyPClrBY55JgPqCthFGVbxsgbxxRd2jxKCGTS/zpelW0beD8pB4NxVhVw7t2HSvj0m9lfUx5A/zzWw2q0yPHzYHjWEOuDXvWLnhAtL1Gah3XrWsImkL/WjAkoX7au+r00bQ7my+qFr4ekETpFvyUGsOKOAgZrNNZaE2InCx9XF/qVmFQwNGBVevs42n31K9+5oqFxw0GURc22UayXjBenHrY1Z7UJ/FpOCkRsFjWe+SNsLuef2xCm0QMfvwe60pxnGf5v7iNTR/xWZWb8GjWcOFgBtK3FLBM+uTCpatd5aigue1Pngs4yVcp8VphmT+YYuQGIhxm/Fu37w+j0mPBk4+BIy4ett8q52lGJTneJsbHwHGwx/FQYp2Q6wtogCWH8DNLtdt0S1Pi6RICx8JG1nFCluOV9yWLgrrjAI4HfVQNtYu5emw9ri0EyZGWpCNORYxvVuAGZeHgLIuEVZB5UnAqGLryfsLvDx31Gfa6czSSW+D7XRFVZgEyizlRfEm3yJFSaiM+HQ5Ee5ll3SNVgCczkvi+SJ5c+PMMtIV0BLu6RL32P8Lry8pcVHJcZoYlniDcCNJ49Xp+/uk5QK20PP0kLWYP8qsg2zuvl/VyAlQS1bQ7SnjfQ814O7WeF4jX/P/5l//fT2V77svePeNd/gFNam/FN/eZPd9io0B/ojOwMWVsA8/wO1RZvc/nOgTbqfi7okAfDbUe+KDjcVsPq9X81eJPK/g/So476kfWUG1S6vjmcIqYpGkGwT7r4t8FfffdIP7ajmdNlnC2Qto2fWNtixjudRr4a+VLF0uTa4vJF8XKuXbg/Hr33TjffKn3gp/kkkmmWSSSSaZZJJJJplkkkkmmWSS/yf5H6HANgUotAMHAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - bindings
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - bindings/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - events
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - functions
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - functions/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - invocations
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - invocations/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - packages
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - packages/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - rules
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - rules/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - triggers
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - triggers/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ibmcloud.ibm.com
          resources:
          - services/status
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
        serviceAccountName: ibmcloud-operator
      deployments:
      - name: ibmcloud-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ibmcloud-operator
          strategy:
            type: RollingUpdate
          template:
            metadata:
              labels:
                app: ibmcloud-operator
            spec:
              containers:
              - args:
                - -logtostderr=true
                - -v=5
                command:
                - ./manager
                image: registry.ng.bluemix.net/seed/cloud-operators:0.1.1
                imagePullPolicy: Always
                name: ibmcloud-controllers
              imagePullSecrets:
              - name: ibmcloud-operator-pullsecret
              serviceAccountName: ibmcloud-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  labels:
    name: ibmcloud-operator
  links:
  - name: IBM Cloud Service Operator Project
    url: https://github.com/ibm/cloud-operators
  maintainers:
  - email: ibmcloud@ibm.com
    name: IBM
  maturity: alpha
  provider:
    name: IBM
  selector:
    matchLabels:
      name: ibmcloud-operator
  version: 0.1.1
